### ISSUE TITLE
align `set password` with the new model

### ISSUE THREAD

**Issue by jbtrystram** [drogue-iot/drg#157]
The new model for credentials in Drogue cloud is : 
```yaml
spec:
  authentication:
    credentials:
      - UsernamePassword:
          username: String
          password: String
          unique: bool
      -   Password
      -  Certificate
      -  PreSharedKey
```
